export const DATA_SAVE_REQ = 'DATA_SAVE_REQ';
export const DATA_SAVE_SUCCESS = 'DATA_SAVE_SUCCESS';
export const DATA_SAVE_FAIL = 'DATA_SAVE_FAIL';

export const DATA_REMOVE = 'DATA_REMOVE_SUCCESS';
export const DATA_REMOVE_ARRAY = 'DATA_REMOVE_ARRAY';
export const DATA_REMOVE_NON_ARRAY = 'DATA_REMOVE_NON_ARRAY';
